* cl-coreutils

GNU Coreutils in Common Lisp.

My objective with this is to read a bunch of coreutils C code, write a bunch of
CL code, and maybe eventually turn it into a shell-like experience that mostly
works.  Chasing full compatibility is explicitly not the goal, as there are a
lot of edge cases and strange compatibility patches that would muddy the
CL-writing experience very quickly.  Still, I will do a moderate effort in
trying to have a functional library, and at least attempt to document most of
the aspects in which it is not fully equivalent.

** Changes

- ~--help~ is translated to ~:help t~, and has precedence over any other
  functionality.

- ~--version~ is removed.

- Shorthands are removed in favor of the complete name versions.

** Tasks

Any pending tasks will go here as Org headings.

*** < > Move ~basename~ edge cases to tests

#+begin_src common-lisp
  (cl-coreutils:basename "/////" "/")     ; "/"
  (cl-coreutils:basename "/////" nil)     ; "/"
  (cl-coreutils:basename "/home/test/" "/") ; "test"
  (cl-coreutils:basename "/home/test/" nil) ; "test"
  (cl-coreutils:basename "/home/test/" "test") ; "test"
  (cl-coreutils:basename "/home/test" "test")  ; "test"
#+end_src
